In [104]:
import numpy as np

- data prepare

Prepare 2 group of points, we can achieved this by using means and cov, each group has N = 30 points

In [105]:
means = [[2, 2], [4, 2]]
cov = [[.3, .2], [.2, .3]]
N = 20

Assign means[0] to X0, means[1] to X1, and concat both of them as X 

In [106]:
X0 = np.random.multivariate_normal(means[0], cov, N).T
X1 = np.random.multivariate_normal(means[1], cov, N).T

X = np.concatenate((X0, X1), axis=1)

X



array([[1.87992856, 2.61119362, 2.1034782 , 2.586875  , 2.35761236,
        2.46861921, 1.3778957 , 2.00984748, 2.10104014, 1.8966859 ,
        2.0170055 , 1.92433458, 1.6760871 , 1.20880454, 1.53651199,
        1.3746852 , 2.03455006, 1.45806877, 1.90942496, 2.0012073 ,
        4.03034613, 3.68631657, 4.47007535, 3.48099496, 4.18262141,
        3.64184894, 3.83027877, 4.20053288, 3.93340502, 4.11665783,
        4.32486152, 5.06323271, 3.6642459 , 2.9079072 , 4.20372219,
        3.85837433, 4.27867334, 3.77240362, 2.69342755, 3.27187984],
       [2.12039108, 2.79021416, 1.63441598, 2.42423075, 1.88982128,
        2.39166952, 2.03600591, 1.90641967, 1.68247878, 1.94265607,
        2.19675706, 3.04695087, 1.19228084, 1.80181994, 2.54166199,
        2.45847555, 1.84700584, 1.24646884, 1.72723196, 1.81304561,
        2.09238119, 1.60664521, 2.57694005, 2.05055795, 2.25416678,
        1.60647215, 1.6596614 , 1.98512509, 1.57606183, 2.18085299,
        1.63617628, 1.65067107, 1.19070097, 0.7

Generate labels for X (X0 = 1, X1 = -1)

In [107]:
Y = np.concatenate((np.ones((1, N)), -1*np.ones((1, N))), axis=1).flatten()
Y

array([ 1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,
        1.,  1.,  1.,  1.,  1.,  1.,  1., -1., -1., -1., -1., -1., -1.,
       -1., -1., -1., -1., -1., -1., -1., -1., -1., -1., -1., -1., -1.,
       -1.])

Add ones vector to X

In [108]:
X = np.concatenate((np.ones((1, X.shape[1])), X), axis=0)


In [109]:
X.shape

(3, 40)

- Perceptron activation function

In [110]:
def activation(w, X):
    return np.sign(w.T @ X)

- Function to check coverge

In [111]:
def check_accuracy(w, X, y_true):
    preds = activation(w, X).flatten()
    acc = np.mean(preds == y_true)
    return acc

- Perceptron function

In [112]:
def perceptron(X, y, w_init, max_iter=60, eta=0.1, tol=1e-4):
    w = w_init

    prev_acc = 0
    misclassified = False
    converged = False

    for _ in range(max_iter):
        random_index = np.random.permutation(X.shape[1])
        X_shuffled, Y_shuffled = X[:, random_index], y[random_index]
        for i in range(len(X_shuffled)):
            xi = X_shuffled[:, i].reshape(-1, 1)
            yi = Y_shuffled[i]

            pred_label = activation(w, xi)
            if (pred_label != yi):
                misclassified = True
                w += eta * yi*xi

        acc = check_accuracy(w, X, Y)
        if (np.abs(acc - prev_acc) < tol):
            converged = True
            break
        else:
            prev_acc = acc

        if (misclassified == False):
            converged = True
            break
    if (converged == False):
        print("Not converged yet!")
    return w

In [127]:
w_init = np.random.randn(X.shape[0], 1)
best_w = perceptron(X, Y, w_init, max_iter=100)
# w_init.shape
best_w

array([[0.10366007],
       [2.7553868 ],
       [0.86203338]])

Read this for more info: https://machinelearningcoban.com/2017/01/21/perceptron/