In [53]:
import numpy as np
import pandas as pd
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score, confusion_matrix

## Read data

In [54]:
glass = pd.read_csv("../../data/glass.csv")
glass

Id_Number       RI     Na    Mg    Al     Si     K    Ca    Ba   Fe  Type
0            1  1.52101  13.64  4.49  1.10  71.78  0.06  8.75  0.00  0.0     1
1            2  1.51761  13.89  3.60  1.36  72.73  0.48  7.83  0.00  0.0     1
2            3  1.51618  13.53  3.55  1.54  72.99  0.39  7.78  0.00  0.0     1
3            4  1.51766  13.21  3.69  1.29  72.61  0.57  8.22  0.00  0.0     1
4            5  1.51742  13.27  3.62  1.24  73.08  0.55  8.07  0.00  0.0     1
..         ...      ...    ...   ...   ...    ...   ...   ...   ...  ...   ...
209        210  1.51623  14.14  0.00  2.88  72.61  0.08  9.18  1.06  0.0     7
210        211  1.51685  14.92  0.00  1.99  73.06  0.00  8.40  1.59  0.0     7
211        212  1.52065  14.36  0.00  2.02  73.42  0.00  8.44  1.64  0.0     7
212        213  1.51651  14.38  0.00  1.94  73.61  0.00  8.48  1.57  0.0     7
213        214  1.51711  14.23  0.00  2.08  73.36  0.00  8.62  1.67  0.0     7

[214 rows x 11 columns]

## Get X, Y 

In [55]:
X = glass.drop(columns=["Id_Number", "Type"])
Y = glass["Type"]
classes = Y.unique()
print(classes)

[1 2 3 5 6 7]


## split train test

In [56]:
X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size=0.25, random_state=192)
Y_test.shape

(54,)

In [57]:
model = LogisticRegression(multi_class="multinomial", max_iter=200000, solver="sag")
model.fit(X_train, Y_train)

LogisticRegression(max_iter=200000, multi_class='multinomial', solver='sag')

In [58]:
Y_predicts = model.predict(X_test)
Y_predicts

array([2, 1, 2, 7, 7, 2, 2, 1, 2, 2, 5, 2, 1, 2, 1, 2, 1, 7, 1, 1, 1, 1,
       2, 7, 2, 2, 1, 2, 2, 6, 2, 1, 2, 1, 1, 7, 2, 1, 2, 2, 1, 1, 1, 2,
       7, 7, 1, 2, 2, 1, 2, 1, 2, 2])

In [59]:
acc = accuracy_score(Y_test, Y_predicts)
confusion_mat = confusion_matrix(Y_test, Y_predicts)

print(acc)
print(confusion_mat)

0.6111111111111112
[[14 10  0  0  0  0]
 [ 5 12  0  0  0  0]
 [ 1  1  0  0  0  0]
 [ 0  2  0  1  0  0]
 [ 0  0  0  0  1  2]
 [ 0  0  0  0  0  5]]
