In [2]:
import numpy as np

In [3]:
A1 = np.array([[5, 2, 2], [4, 1, 3], [1, 2, 1]])
A2 = np.array([[1, 3 ,5], [4, 2, 2], [1, 1, 2]])

B1 = np.array([[5, 2, 2], [4, 1, 3], [1, 2, 1], [3, 1, 2]])
B2 = np.array([[1, 3], [4, 2], [1, 1]])

In [4]:
A_add = A1 + A2
A_add

array([[6, 5, 7],
       [8, 3, 5],
       [2, 3, 3]])

2.3.1: Matrix multiply

In [5]:
A = A1 @ A2
B = B1 @ B2

print(A)
print(B)

[[15 21 33]
 [11 17 28]
 [10  8 11]]
[[15 21]
 [11 17]
 [10  8]
 [ 9 13]]


2.4.1: Matrix inverted

In [6]:
A = [[3, 2, 2, 4], [4, 1, 2, 5], [3, 2, 1, 3], [5, 1, 2, 4]]

In [7]:
A_inv = np.linalg.inv(A)
A_inv

array([[-0.33333333, -0.22222222,  0.22222222,  0.44444444],
       [ 0.33333333, -0.44444444,  0.44444444, -0.11111111],
       [ 1.33333333, -0.77777778, -1.22222222,  0.55555556],
       [-0.33333333,  0.77777778,  0.22222222, -0.55555556]])

2.5.1: Matrix diagonize

In [8]:
A = [[0, 1, 0, 1], [1, 0, 1, 0], [0, 1, 0, 1], [1, 0, 1, 0]]
A_diag = np.diag(A)
A_diag

array([0, 0, 0, 0])

Matrix Determinate: 

In [10]:
A = [[3, 2, 2, 4], [4, 1, 2, 5], [3, 2, 1, 3], [5, 1, 2, 4]]

In [11]:
det_A = np.linalg.det(A)
det_A

-8.999999999999998

Solve Ax = b

In [12]:
b = [1, 1, 1, 1]
np.linalg.solve(A, b)

array([ 0.11111111,  0.22222222, -0.11111111,  0.11111111])